[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
stable_fun = "4g4JPJgeD3V8sgbzKrjsa5zW2XiVvsNdKTzY2UhdhMaN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
